#!/bin/sh

if [ -z "$(git status --untracked-files=no --porcelain)" ]; then
    docker build -t lilactown/lilac.town . \
           --build-arg GIT_COMMIT=$(git rev-parse --verify HEAD)
else
    echo "Uncommitted changes! Not deploying."
    exit 1
fi
